services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    # volumes: #uncomment this to persist data
    #   - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app/server
    command: sh -c "npx prisma migrate deploy --schema=./prisma/schema.prisma"
    env_file:
      - ".env"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - migrate
    env_file:
      - ".env"
      - "server/.env"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - server
    env_file:
      - "client/.env"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
# volumes:
# postgres_data:
